{% set name = "tianshou" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thu-ml/tianshou/releases/download/v{{ version }}/tianshou-{{ version }}.tar.gz
  sha256: 7a4fe27670e7e8168cbf163fe4a2aec848e13f3756069c9b633582972b26860c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gym >=0.15.4
    - tqdm
    - tensorboard
    - pytorch >=1.4.0
    - numba >=0.51.0
    - h5py >=2.10.0

test:
  imports:
    - tianshou

about:
  home: https://github.com/thu-ml/tianshou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tianshou is an elegant, flexible, and superfast PyTorch deep reinforcement learning platform.
  doc_url: https://tianshou.readthedocs.io/
  dev_url: https://github.com/thu-ml/tianshou

extra:
  recipe-maintainers:
    - Trinkle23897
