{% set name = "tianshou" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thu-ml/tianshou/releases/download/v{{ version }}/tianshou-{{ version }}.tar.gz
  sha256: c92489128182cff5c9954336ce652ec187604e14465b4cb672d3e8b3d262e2ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gym >=0.15.4
    - numpy >=1.16.1
    - tqdm
    - tensorboard
    - pytorch >=1.4.0
    - numba >=0.51.0
    - h5py >=2.10.0

test:
  imports:
    - tianshou

about:
  home: https://github.com/thu-ml/tianshou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tianshou is an elegant, flexible, and superfast PyTorch deep reinforcement learning library.
  doc_url: https://tianshou.readthedocs.io/
  dev_url: https://github.com/thu-ml/tianshou

extra:
  recipe-maintainers:
    - Trinkle23897
