{% set name = "tianshou" %}
{% set version = "0.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thu-ml/tianshou/releases/download/v{{ version }}/tianshou-{{ version }}.tar.gz
  sha256: c97ae1c689a9e63df527301b1c6c8ce8661819909efb7d8b632ec9eb4ab62fda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - gym >=0.15.4
    - numpy >=1.16.1
    - tqdm
    - tensorboard >=2.5.0
    - pytorch >=1.4.0
    - numba >=0.51.0
    - h5py >=2.10.0

test:
  imports:
    - tianshou

about:
  home: https://github.com/thu-ml/tianshou
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tianshou is an elegant, flexible, and superfast PyTorch deep reinforcement learning library.
  doc_url: https://tianshou.readthedocs.io/
  dev_url: https://github.com/thu-ml/tianshou

extra:
  recipe-maintainers:
    - Trinkle23897
